=== godotengine/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="enums" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="enum" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="description" minOccurs="0" />
										<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="name" />
														<xs:attribute type="xs:string" name="value" />
														<xs:attribute type="xs:string" name="deprecated" use="optional" />
														<xs:attribute type="xs:string" name="experimental" use="optional" />
														<xs:attribute type="xs:string" name="keywords" use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" />
									<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" use="optional" />
			<xs:attribute type="xs:string" name="api_type" use="optional" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== godotengine/godot/modules/visual_shader/doc_classes/VisualShaderNodeTransformVecMult.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="VisualShaderNodeTransformVecMult" inherits="VisualShaderNode" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		Multiplies a [Transform3D] and a [Vector3] within the visual shader graph.
	</brief_description>
	<description>
		A multiplication operation on a transform (4×4 matrix) and a vector, with support for different multiplication operators.
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="operator" type="int" setter="set_operator" getter="get_operator" enum="VisualShaderNodeTransformVecMult.Operator" default="0">
			The multiplication type to be performed.
		</member>
	</members>
	<enums>
		<enum name="Operator">
			<constant name="OP_AxB" value="0">
				Multiplies transform [code]a[/code] by the vector [code]b[/code].
			</constant>
			<constant name="OP_BxA" value="1">
				Multiplies vector [code]b[/code] by the transform [code]a[/code].
			</constant>
			<constant name="OP_3x3_AxB" value="2">
				Multiplies transform [code]a[/code] by the vector [code]b[/code], skipping the last row and column of the transform.
			</constant>
			<constant name="OP_3x3_BxA" value="3">
				Multiplies vector [code]b[/code] by the transform [code]a[/code], skipping the last row and column of the transform.
			</constant>
			<constant name="OP_MAX" value="4">
				Represents the size of the [enum Operator] enum.
			</constant>
		</enum>
	</enums>
</class>

=== godotengine/godot/modules/openxr/doc_classes/OpenXRFutureExtension.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="OpenXRFutureExtension" inherits="OpenXRExtensionWrapper" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		The OpenXR Future extension allows for asynchronous APIs to be used.
	</brief_description>
	<description>
		This is a support extension in OpenXR that allows other OpenXR extensions to start asynchronous functions and get a callback after this function finishes. It is not intended for consumption within GDScript but can be accessed from GDExtension.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="cancel_future">
			<return type="void" />
			<param index="0" name="future" type="int" />
			<description>
				Cancel an in-progress future. [param future] must be a [code]XrFutureEXT[/code] value previously returned by an API that started an asynchronous function.
			</description>
		</method>
		<method name="get_active" qualifiers="const">
			<return type="bool" />
			<description>
				Returns [code]true[/code] if futures are available in the OpenXR runtime used. This function will only return a usable result after OpenXR has been initialized.
			</description>
		</method>
		<method name="register_future">
			<return type="void" />
			<param index="0" name="future" type="int" />
			<param index="1" name="callable" type="Callable" />
			<description>
				Register the [param callable] to invoke after a future completes processing. [param future] must be a [code]XrFutureEXT[/code] value previously returned by an API that started an asynchronous function.
			</description>
		</method>
	</methods>
</class>

=== godotengine/godot/modules/openxr/doc_classes/OpenXRSpatialContainerExtension.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="OpenXRSpatialContainerExtension" inherits="OpenXRExtensionWrapper" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		OpenXR extension that handles spatial containers.
	</brief_description>
	<description>
		OpenXR extension that handles spatial containers. Enabling this extension will automatically create a main spatial container, and update the lifecycle of the XR application.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_spatial_container_bounds">
			<return type="Vector3" />
			<description>
				Retrieves the bounds of the main spatial container.
			</description>
		</method>
		<method name="get_spatial_container_state">
			<return type="OpenXRSpatialContainerState" />
			<description>
				Retrieves the [OpenXRSpatialContainerState] of the main spatial container.
			</description>
		</method>
		<method name="get_supported_bounds_modes">
			<return type="Array" />
			<description>
				Returns an array of supported spatial container bounds mode, see [enum OpenXRSpatialContainerState.BoundsMode].
			</description>
		</method>
		<method name="is_enabled" qualifiers="const">
			<return type="bool" />
			<description>
				Returns [code]true[/code] if spatial containers are enabled in the project settings and available on the current runtime.
			</description>
		</method>
		<method name="is_spatial_container_active" qualifiers="const">
			<return type="bool" />
			<description>
				Returns [code]true[/code] if the main spatial container is active.
			</description>
		</method>
		<method name="request_spatial_container_bounds_mode">
			<return type="bool" />
			<param index="0" name="bounds_mode" type="int" enum="OpenXRSpatialContainerState.BoundsMode" />
			<description>
				Sends a request to the runtime to update the bounds mode of the main spatial container.
				If the request is accepted, [signal spatial_container_bounds_changed] will be emitted with the updated bounds mode.
				Otherwise, [signal spatial_container_bounds_mode_request_denied] will be emitted.
			</description>
		</method>
		<method name="request_spatial_container_visible">
			<return type="bool" />
			<param index="0" name="visible" type="bool" />
			<description>
				Sends a request to the runtime to update the visibility of the spatial container.
				If the request is accepted, [signal spatial_container_visible_changed] will be emitted with the updated visibility.
				Otherwise, [signal spatial_container_visible_request_denied] will be emitted.
			</description>
		</method>
	</methods>
	<signals>
		<signal name="spatial_container_bounds_changed">
			<param index="0" name="spatial_container_rid" type="RID" />
			<param index="1" name="spatial_container_infinite_bounds" type="bool" />
			<param index="2" name="spatial_container_bounds_mode" type="int" />
			<param index="3" name="spatial_container_bounds" type="Vector3" />
			<description>
				Emitted when the bounds of the spatial container specified by [param spatial_container_rid] are updated.
			</description>
		</signal>
		<signal name="spatial_container_bounds_mode_request_denied">
			<param index="0" name="spatial_container_rid" type="RID" />
			<description>
				Emitted when a request to update the bounds mode of the spatial container specified by [param spatial_container_rid] is denied by the runtime.
			</description>
		</signal>
		<signal name="spatial_container_closed">
			<param index="0" name="spatial_container_rid" type="RID" />
			<description>
				Emitted when the spatial container specified by [param spatial_container_rid] is closed.
			</description>
		</signal>
		<signal name="spatial_container_interactable_changed">
			<param index="0" name="spatial_container_rid" type="RID" />
			<param index="1" name="spatial_container_interactable" type="bool" />
			<description>
				Emitted when the interactability of the spatial container specified by [param spatial_container_rid] is updated.
			</description>
		</signal>
		<signal name="spatial_container_visible_changed">
			<param index="0" name="spatial_container_rid" type="RID" />
			<param index="1" name="spatial_container_visible" type="bool" />
			<description>
				Emitted when the visibility of the spatial container specified by [param spatial_container_rid] is updated.
			</description>
		</signal>
		<signal name="spatial_container_visible_request_denied">
			<param index="0" name="spatial_container_rid" type="RID" />
			<description>
				Emitted when the runtime denies the visibility request of the spatial container specified by [param spatial_container_rid].
			</description>
		</signal>
	</signals>
</class>

=== godotengine/godot/doc/classes/MultiMeshInstance3D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MultiMeshInstance3D" inherits="GeometryInstance3D" version="4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Node that instances a [MultiMesh].
	</brief_description>
	<description>
		[MultiMeshInstance3D] is a specialized node to instance [GeometryInstance3D]s based on a [MultiMesh] resource.
		This is useful to optimize the rendering of a high amount of instances of a given mesh (for example trees in a forest or grass strands).
	</description>
	<tutorials>
		<link title="Animating thousands of fish with MultiMeshInstance">https://docs.godotengine.org/en/latest/tutorials/3d/vertex_animation/animating_thousands_of_fish.html</link>
		<link title="Using MultiMeshInstance">https://docs.godotengine.org/en/latest/tutorials/3d/using_multi_mesh_instance.html</link>
		<link title="Optimization using MultiMeshes">https://docs.godotengine.org/en/latest/tutorials/optimization/using_multimesh.html</link>
	</tutorials>
	<methods>
	</methods>
	<members>
		<member name="multimesh" type="MultiMesh" setter="set_multimesh" getter="get_multimesh">
			The [MultiMesh] resource that will be used and shared among all instances of the [MultiMeshInstance3D].
		</member>
	</members>
	<constants>
	</constants>
</class>

=== godotengine/godot/doc/classes/MicrophoneFeed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MicrophoneFeed" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		A microphone feed gives you access to a single physical microphone attached to your device.
	</brief_description>
	<description>
		A microphone feed gives you access to a single physical microphone attached to your device.
		When enabled, Godot will start acquiring stereo sample frames at the [method AudioServer.get_input_mix_rate]
		and writing them into an internal buffer of size [method get_input_buffer_size].
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_buffer_length_frames">
			<return type="int" />
			<description>
				Returns the absolute size of the microphone input buffer.
				This is set as some multiple of the audio latency and can be used to
				estimate the minimum rate at which the frames are fetched.
			</description>
		</method>
		<method name="get_frames">
			<return type="PackedVector2Array" />
			<param index="0" name="frames" type="int" />
			<description>
				Gets the next [param frames] audio samples from the internal microphone buffer.
				The buffer is filled at the rate of [method AudioServer.get_input_mix_rate] frames per second when [param feed_is_active] is true.
				Returns a [PackedVector2Array] containing exactly [param frames] audio samples if available, or an empty [PackedVector2Array].
				The samples are signed floating-point PCM between [code]-1[/code] and [code]1[/code]. You will have to scale them if you want to use them as 8 or 16-bit integer samples. ([code]v = 0x7fff * samples[0].x[/code])
			</description>
		</method>
		<method name="get_frames_available">
			<return type="int" />
			<description>
				Returns the number of frames available to read using [method get_frames].
			</description>
		</method>
		<method name="get_name" qualifiers="const">
			<return type="String" />
			<description>
				Returns the microphone's name.
			</description>
		</method>
		<method name="set_name">
			<return type="void" />
			<param index="0" name="name" type="String" />
			<description>
				Sets the microphone's name.
			</description>
		</method>
	</methods>
	<members>
		<member name="feed_is_active" type="bool" setter="set_active" getter="is_active" default="false">
			If [code]true[/code], the microphone feed is active.
		</member>
	</members>
</class>

=== godotengine/godot/modules/visual_script/doc_classes/VisualScriptPropertyGet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="VisualScriptPropertyGet" inherits="VisualScriptNode" version="4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<methods>
	</methods>
	<members>
		<member name="base_script" type="String" setter="set_base_script" getter="get_base_script">
		</member>
		<member name="base_type" type="StringName" setter="set_base_type" getter="get_base_type" default="@&quot;Object&quot;">
		</member>
		<member name="basic_type" type="int" setter="set_basic_type" getter="get_basic_type" enum="Variant.Type">
		</member>
		<member name="index" type="StringName" setter="set_index" getter="get_index">
		</member>
		<member name="node_path" type="NodePath" setter="set_base_path" getter="get_base_path">
		</member>
		<member name="property" type="StringName" setter="set_property" getter="get_property" default="@&quot;&quot;">
		</member>
		<member name="set_mode" type="int" setter="set_call_mode" getter="get_call_mode" enum="VisualScriptPropertyGet.CallMode" default="0">
		</member>
	</members>
	<constants>
		<constant name="CALL_MODE_SELF" value="0" enum="CallMode">
		</constant>
		<constant name="CALL_MODE_NODE_PATH" value="1" enum="CallMode">
		</constant>
		<constant name="CALL_MODE_INSTANCE" value="2" enum="CallMode">
		</constant>
	</constants>
</class>
